# -*- coding: utf-8 -*-
"""Time Series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QFTRV41noACcCYZMpbsH7QIExm0G8Bu0
"""

# ==============================
# Imports
# ==============================

import os
import glob
import json
import zipfile
import joblib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    precision_score,
    recall_score,
    f1_score
)

# ==============================
# Configuration
# ==============================

ZIP_PATH = "/content/drive/MyDrive/Oil Well/3w_dataset.zip"   # update if needed
EXTRACT_PATH = "/content/3W_extracted"
TEST_FOLD = 0
CHOSEN_THRESHOLD = 0.90
ALERT_WINDOW = 30

SAVE_DIR = "/content/3w_model_outputs"
os.makedirs(SAVE_DIR, exist_ok=True)

# ==============================
# Configuration
# ==============================

ZIP_PATH = "/content/drive/MyDrive/Oil Well/3w_dataset.zip"   # update if needed
EXTRACT_PATH = "/content/3W_extracted"
TEST_FOLD = 0
CHOSEN_THRESHOLD = 0.90
ALERT_WINDOW = 30

SAVE_DIR = "/content/3w_model_outputs"
os.makedirs(SAVE_DIR, exist_ok=True)

# ==============================
# Mount Drive and Extract Dataset
# ==============================

from google.colab import drive
drive.mount('/content/drive')

os.makedirs(EXTRACT_PATH, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, "r") as zip_ref:
    zip_ref.extractall(EXTRACT_PATH)

print("Dataset extracted.")

# ==============================
# Locate Dataset Root
# ==============================

def find_dataset_root(start_path):
    expected_items = set([str(i) for i in range(9)] + ["folds"])

    for root, dirs, files in os.walk(start_path):
        if expected_items.issubset(set(dirs + files)):
            return root

    return None

base_path = find_dataset_root(EXTRACT_PATH)

print("Dataset root:", base_path)
print("Items:", os.listdir(base_path))

# ==============================
# Locate Dataset Root
# ==============================

def find_dataset_root(start_path):
    expected_items = set([str(i) for i in range(9)] + ["folds"])

    for root, dirs, files in os.walk(start_path):
        if expected_items.issubset(set(dirs + files)):
            return root

    return None

base_path = find_dataset_root(EXTRACT_PATH)

print("Dataset root:", base_path)
print("Items:", os.listdir(base_path))

# ==============================
# Load Fold Definition
# ==============================

folds_path = os.path.join(base_path, "folds")
fold_file_path = os.path.join(folds_path, "folds_clf_02.csv")

folds_df = pd.read_csv(fold_file_path)

print("Fold file shape:", folds_df.shape)
display(folds_df.head())
print(folds_df["fold"].value_counts().sort_index())

# ==============================
# Load Sensor Files Listed in Fold File
# ==============================

all_instances = []

for i, row in folds_df.iterrows():
    instance_path = row["instancia"]

    if not instance_path.endswith(".csv"):
        instance_path = instance_path + ".csv"

    # Construct full_path by directly joining base_path and instance_path
    # The instance_path already includes the numbered directory (e.g., '2/')
    full_path = os.path.join(base_path, instance_path)

    # Check file existence before attempting to read
    if not os.path.exists(full_path) or not os.path.isfile(full_path):
        # print(f"Warning: File does not exist or is not a regular file at {full_path}. Skipping.")
        continue

    temp_df = pd.read_csv(full_path)
    temp_df["source_file"] = instance_path
    temp_df["fold"] = row["fold"]

    if "is_ova" in folds_df.columns:
        temp_df["is_ova"] = row["is_ova"]

    all_instances.append(temp_df)

data = pd.concat(all_instances, ignore_index=True)

print("Combined data shape:", data.shape)
display(data.head())

# ==============================
# Basic Data Inspection
# ==============================

print("Rows:", len(data))
print("Unique source files:", data["source_file"].nunique())

print("\nClass distribution:")
print(data["class"].value_counts(dropna=False))

print("\nMissing values (%):")
display((data.isna().mean() * 100).sort_values(ascending=False))

# ==============================
# Timestamp Processing and Sorting
# ==============================

data["timestamp"] = pd.to_datetime(data["timestamp"])

data = data.sort_values(["source_file", "timestamp"]).reset_index(drop=True)

data["time_diff_seconds"] = (
    data.groupby("source_file")["timestamp"]
    .diff()
    .dt.total_seconds()
)

print("Most common sampling intervals:")
print(data["time_diff_seconds"].value_counts().head())

# ==============================
# Sensor Column Selection and Missing Value Handling
# ==============================

sensor_cols = [
    "P-PDG", "P-TPT", "T-TPT", "P-MON-CKP",
    "T-JUS-CKP", "P-JUS-CKGL", "T-JUS-CKGL", "QGL"
]

sensor_cols = [col for col in sensor_cols if col in data.columns]

usable_sensor_cols = []

for col in sensor_cols:
    non_missing_ratio = data[col].notna().mean()

    if non_missing_ratio > 0.20:
        usable_sensor_cols.append(col)

print("Usable sensor columns:", usable_sensor_cols)

for col in usable_sensor_cols:
    data[col] = (
        data.groupby("source_file")[col]
        .transform(lambda x: x.ffill().bfill())
    )

print("Missing values after cleaning:")
display((data[usable_sensor_cols].isna().mean() * 100).sort_values(ascending=False))

# ==============================
# Binary Target Creation
# ==============================

data = data.dropna(subset=["class"]).copy()

data["target_abnormal"] = (data["class"] != 0).astype(int)

print("Binary target distribution:")
print(data["target_abnormal"].value_counts())

# ==============================
# Lag and Rolling-Window Feature Engineering
# ==============================

for col in usable_sensor_cols:
    data[f"{col}_lag1"] = data.groupby("source_file")[col].shift(1)
    data[f"{col}_lag5"] = data.groupby("source_file")[col].shift(5)
    data[f"{col}_lag60"] = data.groupby("source_file")[col].shift(60)

    data[f"{col}_roll60_mean"] = (
        data.groupby("source_file")[col]
        .transform(lambda x: x.shift(1).rolling(window=60).mean())
    )

    data[f"{col}_roll60_std"] = (
        data.groupby("source_file")[col]
        .transform(lambda x: x.shift(1).rolling(window=60).std())
    )

    data[f"{col}_roll60_max"] = (
        data.groupby("source_file")[col]
        .transform(lambda x: x.shift(1).rolling(window=60).max())
    )

engineered_feature_cols = [
    col for col in data.columns
    if col in usable_sensor_cols or "_lag" in col or "_roll" in col
]

data_model = data.dropna(subset=["target_abnormal"]).copy()
data_model = data_model.dropna(subset=engineered_feature_cols).copy()

print("Modeling data shape:", data_model.shape)

# ==============================
# Fold-Based Train/Test Split
# ==============================

train_data = data_model[data_model["fold"] != TEST_FOLD].copy()
test_data = data_model[data_model["fold"] == TEST_FOLD].copy()

drop_cols = [
    "timestamp", "class", "target_abnormal", "source_file",
    "fold", "is_ova", "time_diff_seconds"
]

feature_cols = [
    col for col in train_data.columns
    if col not in drop_cols and train_data[col].dtype != "object"
]

X_train = train_data[feature_cols].astype("float32")
y_train = train_data["target_abnormal"]

X_test = test_data[feature_cols].astype("float32")
y_test = test_data["target_abnormal"]

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("Number of features:", len(feature_cols))

# ==============================
# Model Training
# ==============================

rf_model = RandomForestClassifier(
    n_estimators=30,
    max_depth=12,
    min_samples_leaf=10,
    max_samples=0.5,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

print("Model training completed.")

# ==============================
# Initial Model Evaluation
# ==============================

y_pred_default = rf_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_default))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_default))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_default, zero_division=0))

# ==============================
# Threshold Tuning
# ==============================

y_proba = rf_model.predict_proba(X_test)[:, 1]

thresholds = np.arange(0.1, 0.91, 0.05)
threshold_results = []

for threshold in thresholds:
    y_pred_threshold = (y_proba >= threshold).astype(int)

    threshold_results.append({
        "threshold": threshold,
        "accuracy": accuracy_score(y_test, y_pred_threshold),
        "precision_abnormal": precision_score(y_test, y_pred_threshold, zero_division=0),
        "recall_abnormal": recall_score(y_test, y_pred_threshold, zero_division=0),
        "f1_abnormal": f1_score(y_test, y_pred_threshold, zero_division=0)
    })

threshold_results_df = pd.DataFrame(threshold_results)

display(threshold_results_df)

# ==============================
# Final Evaluation with Tuned Threshold
# ==============================

y_pred_tuned = (y_proba >= CHOSEN_THRESHOLD).astype(int)

print("Chosen threshold:", CHOSEN_THRESHOLD)
print("Accuracy:", accuracy_score(y_test, y_pred_tuned))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_tuned))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_tuned, zero_division=0))

# ==============================
# Operational Alert Logic
# ==============================

alert_df = test_data.copy()
alert_df["predicted_probability_abnormal"] = y_proba
alert_df["predicted_label"] = y_pred_tuned

alert_df["raw_alert"] = (
    alert_df["predicted_probability_abnormal"] >= CHOSEN_THRESHOLD
).astype(int)

alert_df["persistent_alert"] = (
    alert_df.groupby("source_file")["raw_alert"]
    .transform(lambda x: x.rolling(window=ALERT_WINDOW, min_periods=ALERT_WINDOW).sum())
)

alert_df["persistent_alert"] = (
    alert_df["persistent_alert"] >= ALERT_WINDOW
).astype(int)

print("Raw alert count:")
print(alert_df["raw_alert"].value_counts())

print("\nPersistent alert count:")
print(alert_df["persistent_alert"].value_counts())

# ==============================
# Cell 19: Operational Alert Summary Table
# ==============================

import pandas as pd

alert_summary = []

for source_file, group in alert_df.groupby("source_file"):
    group = group.sort_values("timestamp")

    # Model alert information
    max_prob = group["predicted_probability_abnormal"].max()
    raw_alert_count = group["raw_alert"].sum()
    persistent_alert_count = group["persistent_alert"].sum()

    # Actual file-level status
    # If any row in the file is abnormal, the file is considered abnormal
    actual_file_abnormal = int(group["target_abnormal"].max())

    # First time persistent alert is triggered
    persistent_alert_rows = group[group["persistent_alert"] == 1]

    if len(persistent_alert_rows) > 0:
        first_alert_time = persistent_alert_rows["timestamp"].iloc[0]
        status = "Persistent abnormal alert"
        predicted_file_alert = 1

    elif raw_alert_count > 0:
        first_alert_time = group[group["raw_alert"] == 1]["timestamp"].iloc[0]
        status = "Raw warning only"
        predicted_file_alert = 1

    else:
        first_alert_time = None
        status = "Normal"
        predicted_file_alert = 0

    # Compare actual status with predicted alert
    if actual_file_abnormal == 1 and predicted_file_alert == 1:
        alert_outcome = "True alert"
    elif actual_file_abnormal == 0 and predicted_file_alert == 1:
        alert_outcome = "False alert"
    elif actual_file_abnormal == 1 and predicted_file_alert == 0:
        alert_outcome = "Missed alert"
    else:
        alert_outcome = "Correct normal"

    # Operational priority
    if status == "Persistent abnormal alert" and max_prob >= 0.95:
        priority = "High"
    elif status == "Persistent abnormal alert":
        priority = "Medium"
    elif status == "Raw warning only":
        priority = "Low / Watch"
    else:
        priority = "No action"

    alert_summary.append({
        "source_file": source_file,
        "actual_file_abnormal": actual_file_abnormal,
        "predicted_file_alert": predicted_file_alert,
        "max_abnormal_probability": round(max_prob, 4),
        "raw_alert_count": int(raw_alert_count),
        "persistent_alert_count": int(persistent_alert_count),
        "first_alert_time": first_alert_time,
        "status": status,
        "alert_outcome": alert_outcome,
        "priority": priority
    })

alert_summary_df = pd.DataFrame(alert_summary)

# Sort like an operations dashboard: alerts first, normal cases later
alert_summary_df = alert_summary_df.sort_values(
    ["predicted_file_alert", "persistent_alert_count", "max_abnormal_probability"],
    ascending=False
).reset_index(drop=True)

display(alert_summary_df.head(30))

print("\nAlert outcome summary:")
print(alert_summary_df["alert_outcome"].value_counts())

print("\nPriority summary:")
print(alert_summary_df["priority"].value_counts())

# ==============================
# Cell 20: Visualization of Alert Behavior
# ==============================

import matplotlib.pyplot as plt

# Select a file with a persistent alert if available
alert_files = alert_summary_df[
    alert_summary_df["status"] == "Persistent abnormal alert"
]["source_file"].tolist()

if len(alert_files) > 0:
    selected_file = alert_files[0]
else:
    selected_file = alert_df["source_file"].iloc[0]

single_file_df = alert_df[alert_df["source_file"] == selected_file].copy()
single_file_df = single_file_df.sort_values("timestamp")

print("Selected file:", selected_file)
print("Shape:", single_file_df.shape)
print("\nActual target distribution:")
print(single_file_df["target_abnormal"].value_counts())

# Plot predicted probability, threshold, actual label, and persistent alert
plt.figure(figsize=(16, 5))

plt.plot(
    single_file_df["timestamp"],
    single_file_df["predicted_probability_abnormal"],
    label="Predicted abnormal probability"
)

plt.axhline(
    y=CHOSEN_THRESHOLD,
    linestyle="--",
    label=f"Decision threshold = {CHOSEN_THRESHOLD}"
)

plt.plot(
    single_file_df["timestamp"],
    single_file_df["target_abnormal"],
    label="Actual abnormal label",
    linewidth=2
)

plt.plot(
    single_file_df["timestamp"],
    single_file_df["persistent_alert"],
    label=f"Persistent alert ({ALERT_WINDOW}s rule)",
    alpha=0.8
)

plt.title(f"Predicted Probability, Actual Label, and Alert Logic\n{selected_file}")
plt.xlabel("Time")
plt.ylabel("Probability / Label / Alert")
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ==============================
# Cell 21: Explainability using Feature Importance and SHAP
# ==============================

import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------
# 1. Random Forest Feature Importance
# ------------------------------

feature_importance_df = pd.DataFrame({
    "feature": feature_cols,
    "importance": rf_model.feature_importances_
}).sort_values("importance", ascending=False)

print("Top 20 important features:")
display(feature_importance_df.head(20))

top_features = feature_importance_df.head(15).sort_values("importance")

plt.figure(figsize=(10, 6))
plt.barh(top_features["feature"], top_features["importance"])
plt.title("Top 15 Features Used by the Model")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.tight_layout()
plt.show()


# ------------------------------
# 2. SHAP Explainability
# ------------------------------

# Install SHAP if not already installed
try:
    import shap
except ImportError:
    !pip install shap -q
    import shap

# Use a small sample to keep computation fast
sample_size = 500

X_sample = X_test.sample(
    n=min(sample_size, len(X_test)),
    random_state=42
)

# Create SHAP explainer for the trained tree model
explainer = shap.TreeExplainer(rf_model)

# Calculate SHAP values
shap_values = explainer.shap_values(X_sample)

print("SHAP values calculated.")

# For binary classification, SHAP may return either:
# - a list [class_0_values, class_1_values]
# - or a 3D array depending on SHAP/sklearn version

if isinstance(shap_values, list):
    shap_values_abnormal = shap_values[1]
else:
    # If shape is (samples, features, classes), select abnormal class index 1
    if len(shap_values.shape) == 3:
        shap_values_abnormal = shap_values[:, :, 1]
    else:
        shap_values_abnormal = shap_values

# SHAP bar summary plot for abnormal class
shap.summary_plot(
    shap_values_abnormal,
    X_sample,
    feature_names=feature_cols,
    plot_type="bar"
)

# ==============================
# Save Model Artifacts
# ==============================

joblib.dump(rf_model, os.path.join(SAVE_DIR, "rf_3w_abnormal_detector.joblib"))

with open(os.path.join(SAVE_DIR, "chosen_threshold.json"), "w") as f:
    json.dump({"chosen_threshold": CHOSEN_THRESHOLD}, f)

with open(os.path.join(SAVE_DIR, "feature_columns.json"), "w") as f:
    json.dump(feature_cols, f)

threshold_results_df.to_csv(
    os.path.join(SAVE_DIR, "threshold_tuning_results.csv"),
    index=False
)

alert_summary_df.to_csv(
    os.path.join(SAVE_DIR, "operational_alert_summary.csv"),
    index=False
)

print("Artifacts saved.")